### ISSUE TITLE
[cpp] FlxUIList compile error

### ISSUE THREAD

**Issue by MSGhero** [HaxeFlixel/flixel-ui#110]
https://github.com/HaxeFlixel/flixel-ui/blob/dev/flixel/addons/ui/FlxUIList.hx#L218-L228

`prevButton` and `nextButton` are `IFlxUIButton`, but their x and y props are trying to be accessed which aren't defined in that interface.
`./src/flixel/addons/ui/FlxUIList.cpp(771) : error C2039: 'set_x' : is not a member of 'flixel::addons::ui::interfaces::IFlxUIButton_obj'` times 8 errors here.

**Comment by Gama11** [comment]
This only happens with recent dev versions of Haxe. I reduced the issue and reported it on the Haxe repo here: HaxeFoundation/haxe#4343
