### ISSUE TITLE
Dev not working with dev version of the other flixel repos

### ISSUE THREAD

**Issue by guifes** [HaxeFlixel/flixel-ui#116]
actuate: 1.8.3 1.8.4 1.8.5 [1.8.6]
box2d: [1.2.3]
flixel-addons: git [dev:/usr/lib/haxe/lib/flixel-addons/git]
flixel-demos: git [dev:/usr/lib/haxe/lib/flixel-demos/git]
flixel-templates: [1.0.2]
flixel-tools: 1.0.5 [1.1.0]
flixel-ui: git [dev:/usr/lib/haxe/lib/flixel-ui/git]
flixel: 3.3.8 git [dev:/usr/lib/haxe/lib/flixel/git]
haxelib_client: 3.1.0-rc.4 3.2.0-rc.1 3.2.0-rc.2 [3.2.0-rc.3]
hxcpp: [3.2.102] 3.2.37 3.2.81 3.2.94
layout: [1.2.0]
lime-samples: 2.2.0 2.3.0 [2.4.0]
lime: 2.2.1 2.2.2 2.3.0 2.3.1 2.3.2 2.3.3 2.4.0 2.4.1 2.4.2 2.4.3 2.4.4 2.4.5 2.4.6 2.4.7 2.4.8 [2.4.9]
openfl-samples: 2.2.2 [3.1.0]
openfl: 2.2.8 3.0.0-beta.2 3.0.0-beta.3 3.0.1 3.0.2 3.0.3 3.0.4 3.0.5 3.0.6 3.0.8 3.1.0 3.1.1 3.1.2 [3.1.3]
swf: 1.8.0 1.8.1 1.8.2 1.8.4 1.8.5 1.8.6 1.8.7 1.8.8 [1.8.9]

Now I'm getting this when building:

/usr/lib/haxe/lib/flixel-ui/git/flixel/addons/ui/FlxUI.hx:580: characters 20-35 : Xml has no field children (Suggestion: _children)
/usr/lib/haxe/lib/flixel-ui/git/flixel/addons/ui/FlxUI.hx:580: characters 20-35 : You can't iterate on a Dynamic value, please specify Iterator or Iterable

**Comment by larsiusprime** [comment]
What version of Haxe are you using? (type haxe in the command line).

Is it 3.2.0 or 3.1.3 ?

**Comment by larsiusprime** [comment]
for context: we detected that this was breaking with Haxe 3.1.3, [see here](https://github.com/HaxeFlixel/flixel-ui/pull/114#issuecomment-121291129), but thought that everyone using latest dev branches was also using latest Haxe 3.2.0. If you are indeed using 3.1.3 and have a good reason you can't upgrade to 3.2.0, I can look into restoring compatibility with a quick patch.

**Comment by guifes** [comment]
You are right. I've just updated to 3.2.0, everything works fine.
