### ISSUE TITLE
Changing cursor graphic issue

### ISSUE THREAD

**Issue by ivodopiviz** [HaxeFlixel/flixel-ui#141]
I'm simply using loadGraphic() to change the cursor image, but after doing it the cursor ends up in a slighlty off position and I can't choose something using "enter" for example.

Moving it around with the cursor keys seems to "fix it" and then proceeds to work just fine. Am I doing it wrong? Is there a "proper" way to change the cursor image?

Cheers,

**Comment by larsiusprime** [comment]
The usual way is to override the createCursor() function in your FlxUIState class. Here's a simplified version of the one I use:

```
override function createCursor():FlxUICursor 
{
	return new FlxUICursor(onCursorEvent, FlxUICursor.INPUT_KEYS, FlxUICursor.KEYS_TAB, cursorAsset);
}
```

A simpler load function to use at runtime, or making sure loadGraphic() is bug-free might be nice, will have to look into it when I have the time...

What happens if you call updateHitBox() or drawFrame() on the cursor after setting loadGraphic()?

**Comment by ivodopiviz** [comment]
Hmmm... 
According to this: https://github.com/HaxeFlixel/flixel-ui/blob/master/flixel/addons/ui/FlxUIState.hx
and the Haxe compiler, there's no such a thing as a "createCursor" method to override.

updateHitbox() and drawFrame() don't do anything either by themselves or called together in sequence.

I tried just doing cursor = new FlxUICursor(blah, blah) but doesn't seem to work either. It has the default graphic and doesn't seem to respond to input.

**Comment by larsiusprime** [comment]
Sorry, I'm talking about the dev version of the library.

**Comment by ivodopiviz** [comment]
Oh, boy. And my deadline approaches :P
Will try the dev version if there isn't much breakage, thanks.

**Comment by larsiusprime** [comment]
Yeah, sorry about that :/ we really need to get flixel 4.x released so I can synch up flixel-ui haxelib release to it. Let me know if you have any trouble.

**Comment by ivodopiviz** [comment]
It seems to depend on flixel 4 and my game uses stuff that flixel 4 refactored / reworked and I just don't have the time to port it right now.

I'm probably going to programmer hell for this, but I just modified my build script to overwrite the "hand" image file. Like most ugly hacks, it works :P

**Comment by larsiusprime** [comment]
Whatever it takes!

**Comment by ivodopiviz** [comment]
Ok, already migrated to the dev version and cursor stuff seems to be working fine.
