### ISSUE TITLE
Scrolling Popups

### ISSUE THREAD

**Issue by ivodopiviz** [HaxeFlixel/flixel-ui#149]
![screen shot 2015-11-24 at 7 11 56 pm](https://cloud.githubusercontent.com/assets/250464/11382865/2acb5084-92e3-11e5-9b6d-56647b5d61a9.png)

This is a little weird: I'm trying to use Popups for retry / success screens but they seem to scroll. I tried setting scrollFactor(0, 0) but doesn't seem to work. 

Should I set the scrolling factor of each element by hand? Do we really need scrolling UI elements?

Cheers!

**Comment by larsiusprime** [comment]
That's weird, popups should have scrollfactor set to 0,0. Where did you set
the scrollfactor value?

On Tue, Nov 24, 2015 at 4:57 PM, Ivan Vodopiviz <notifications@github.com>
wrote:

> [image: screen shot 2015-11-24 at 7 11 56 pm]
> <https://cloud.githubusercontent.com/assets/250464/11382865/2acb5084-92e3-11e5-9b6d-56647b5d61a9.png>
>
> This is a little weird: I'm trying to use Popups for retry / success
> screens but they seem to scroll. I tried setting scrollFactor(0, 0) but
> doesn't seem to work.
>
> Should I set the scrolling factor of each element by hand? Do we really
> need scrolling UI elements?
>
> Cheers!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HaxeFlixel/flixel-ui/issues/149>.
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ivodopiviz** [comment]
After the super.create() in the popup's create() method. As I said, it doesn't work.

The weirdest part is that the popup is created on the fly immediately when the player loses. So I'm not really sure how it ends up scrolled.

**Comment by larsiusprime** [comment]
I'll look into it when I have a chance, this sounds like a real bug.

Things to inspect if you get to it before I do:

1) Throw a timer and break-to-inspect/trace out the scrollfactor value
after a few seconds of updating, see if something is setting scrollfactor
back to not-0
2) Make sure popup is not contained in something else that might have a
scrollfactor set

On Wed, Nov 25, 2015 at 9:25 AM, Ivan Vodopiviz <notifications@github.com>
wrote:

> After the super.create() in the popup's create() method. As I said, it
> doesn't work.
>
> The weirdest part is that the popup is created on the fly immediately when
> the player loses. So I'm not really sure how it ends up scrolled.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HaxeFlixel/flixel-ui/issues/149#issuecomment-159640254>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ivodopiviz** [comment]
Ok, I spammed my stdout with this on one of the popups:

    public override function update(dt:Float):Void
    {
    	super.update(dt);
    	trace("Position: " + x + "/" + y);
    	trace("ScrollFactor: " + scrollFactor.toString());
    }

With this output:

    RetryPopup.hx:64: Position: 0/0
    RetryPopup.hx:65: ScrollFactor: (x: 0 | y: 0)

Guess it's good that no one seems to be setting a scrollFactor just for kicks. It doesn't however, shed any light on what the issue might be.

I'm simply creating the popup dialog and using it with openSubState() on my PlayState. PlayState used to inherit from FlxState but I moved it to FlxUIState just in case.

**Comment by larsiusprime** [comment]
have you checked whether your FlxUIState itself has a scrollfactor set? Or
whether the _ui object in your FlxUIState has a scrollfactor set?

On Wed, Nov 25, 2015 at 12:35 PM, Ivan Vodopiviz <notifications@github.com>
wrote:

> Ok, I spammed my stdout with this on one of the popups:
>
> public override function update(dt:Float):Void
> {
>     super.update(dt);
>     trace("Position: " + x + "/" + y);
>     trace("ScrollFactor: " + scrollFactor.toString());
> }
>
> With this output:
>
> RetryPopup.hx:64: Position: 0/0
> RetryPopup.hx:65: ScrollFactor: (x: 0 | y: 0)
>
> Guess it's good that no one seems to be setting a scrollFactor just for
> kicks. It doesn't however, shed any light on what the issue might be.
>
> I'm simply creating the popup dialog and using it with openSubState() on
> my PlayState. PlayState used to inherit from FlxState but I moved it to
> FlxUIState just in case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HaxeFlixel/flixel-ui/issues/149#issuecomment-159696164>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ivodopiviz** [comment]
FlxUIState itself doesn't seem to have a scrollFactor. And... oh. My PlayState._ui scrollFactor seems to be [1, 1].

Now, PlayState doesn't actually use any GUI elements (no xml is loaded, no flixel-ui control is added) so there's no need for it to be a FlxUIState. In fact, if I change it back to FlxState the popup still scrolls even though there's no _ui to mess up its scrollFactor. It's still reports 0, 0 as scrollfactor though.

**Comment by ivodopiviz** [comment]
Quick update: I haven't been able to track down the issue in FlxUIPopup, but it can be worked around by setting the scrollfactors of each control by hand. So I'm going with that for now.

**Comment by ivodopiviz** [comment]
Sorry to bother, but any news on this issue?

**Comment by larsiusprime** [comment]
Not yet... I suppose what I could do is just make it so that FlxUIPopup will automatically go through and set all its member widgets to have a scrollfactor of 0,0 by default.

**Comment by larsiusprime** [comment]
Hmm, try this first. In my own FlxUIPopup extension, I do these two lines on create:

```
		scrollFactor.set(0, 0);
		_ui.setScrollFactor(0, 0);
```

If that works for you, then I'll probably make this the default behavior.

**Comment by ivodopiviz** [comment]
OK, I tried the following:

```haxe
public override function create():Void
{
	_xml_id = "dialog_popup";
	_makeCursor = true;
	super.create();

	scrollFactor.set(0, 0);
        _ui.setScrollFactor(0, 0);
        // [SNIP}
}
```

And seems to work fine now. FlxUICursor isn't always working correctly, but that's a different issue.

**Comment by larsiusprime** [comment]
Yeah there's an open issue for FlxUICursor that I'm looking into. I'm going to make a commit to lars_latest branch with the default scrollfactor settings for FlxUIPopups.

**Comment by Gama11** [comment]
So now that that's merged this can be closed?

**Comment by larsiusprime** [comment]
Yeah I think so.
