### ISSUE TITLE
Error in FlxUI on Android target

### ISSUE THREAD

**Issue by dleanjeans** [HaxeFlixel/flixel-ui#153]
Building using FlashDevelop, Output window:

`Error: ./src/flixel/addons/ui/FlxUI.cpp: In member function 'virtual flixel::addons::ui::interfaces::IFlxUIWidget flixel::addons::ui::FlxUI_obj::_loadButton(haxe::xml::Fast, hx::Null<bool>, hx::Null<bool>, String)':
./src/flixel/addons/ui/FlxUI.cpp:9673: error: 'class flixel::addons::ui::interfaces::IFlxUIButton_obj' has no member named 'set_visible'`

**Comment by Gama11** [comment]
flixel-ui is incompatible to Haxe 3.2.1 on cpp targets due to a compiler bug, see See https://github.com/HaxeFlixel/flixel-demos/issues/208. As a workaround you could downgrade to Haxe 3.2.0 which doesn't have the bug.
