### ISSUE TITLE
FlxUIDropDownMenu: last item is outside of list

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel-ui#155]
In RPG Interface (somewhat subtle because of the gray background):

![](http://i.imgur.com/ns8NsR8.png)

FlxTween demo:

![](http://i.imgur.com/AsZLej1.png)

**Comment by Gama11** [comment]
Seems like this issue has been around since at least 45b6ee9... going back further than that would require downgrading OpenFL.

**Comment by MSGhero** [comment]
It's been like that for a long time, like since at least July/Aug. I guess I forgot to bring the issue up when I came across it back then :grin:
