### ISSUE TITLE
.name or .id?

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel-ui#189]
The readme mostly/always refers to a "name" attribute as the main identifier in the xml source, but the RPGInterface demo xml always uses "id" instead (and of course, it works.)  This is a bit confusing for a newcomer.  Will they always be able to be used interchangeably?  Or is "name" deprecated / on the way to being deprecated?

**Comment by Gama11** [comment]
`id` was renamed to `name` at some point to avoid confusion with `FlxBasic#ID`. I doubt `id` in XML is going to go because of backwards compatibility.

Perhaps this should be mentioned in the docs somehwere.
