### ISSUE TITLE
FlxUI9SliceSprite renders incorrectly with webgl

### ISSUE THREAD

**Issue by CarlOlson** [HaxeFlixel/flixel-ui#197]
Webgl only renders the corners of 9-sliced sprites.

This can be seen in the RPGInterface demo.
lime test html5 -Dwebgl

**Comment by larsiusprime** [comment]
Thanks for opening this issue, it's been something I've known about for a while but haven't gotten around to fixing yet, good to put up an issue for it so we can make sure we eventually address it.

Does it happen in every browser for you or just some?

**Comment by CarlOlson** [comment]
Every browser. I think I've narrowed it down to the final_pixels.draw call/s. So the error might be in BitmapData's draw method. It might be a problem for the OpenFL devs.

**Comment by Gama11** [comment]
Haha, that actually looks quite funny. :)

![](http://i.imgur.com/g942NyI.png)

**Comment by ttencate** [comment]
Also seeing this. Additionally, my sprites that are composed using `stamp()` do not show up either, also suggesting that this might be either a core HaxeFlixel issue or an OpenFL issue.

**Comment by Gama11** [comment]
This is no longer an issue with OpenFL 8:

![](https://i.imgur.com/vpLUKl0.png)
