### ISSUE TITLE
Crash on neko when creating FlxUIRadioGroup

### ISSUE THREAD

**Issue by Cor-cor** [HaxeFlixel/flixel-ui#203]
haxe 3.4.1
lime 2.9.1
openfl 3.6.1 (legacy)
flixel 3.4.1
flixel-ui 2.2.0

This code:
```
	_radioGroup = new FlxUIRadioGroup(20, 20,
	["id1", "id2"],
	["label1", "label2"]);
```
causes crash when building for neko (flash is OK) if it's in a state that's not in a root source folder (where Main is located) i.e.
source/TestState.hx - will work
source/subfolder/TestState.hx - won't work

Stacktrace:
```
Invalid call
Called from flixel/ui/FlxButton.hx line 592
Called from flixel/addons/ui/FlxUITypedButton.hx line 1166
Called from flixel/addons/ui/FlxUIList.hx line 251
Called from flixel/addons/ui/FlxUIList.hx line 185
Called from flixel/addons/ui/FlxUIList.hx line 161
Called from flixel/addons/ui/FlxUIList.hx line 9
Called from flixel/addons/ui/FlxUIRadioGroup.hx line 120
Called from flixel/addons/ui/FlxUIRadioGroup.hx line 15
Called from wtf/Crash.hx line 14
Called from flixel/FlxGame.hx line 649
Called from flixel/FlxGame.hx line 350
Called from openfl/_legacy/events/EventDispatcher.hx line 98
Called from openfl/_legacy/display/DisplayObject.hx line 182
Called from openfl/_legacy/display/DisplayObject.hx line 70
Called from openfl/_legacy/display/DisplayObject.hx line 362
Called from openfl/_legacy/display/DisplayObjectContainer.hx line 379
Called from openfl/_legacy/display/DisplayObject.hx line 423
Called from openfl/_legacy/display/DisplayObjectContainer.hx line 31
Called from Main.hx line 17
Called from ApplicationMain.hx line 217
Called from ApplicationMain.hx line 217
Called from C:\Haxe\haxe\std/neko/_std/Type.hx line 109
Called from ApplicationMain.hx line 119
Called from openfl/_legacy/Lib.hx line 122
```

Sample project: https://github.com/Cor-cor/flxui-radiogroup-neko-crash

**Comment by Gama11** [comment]
I can reproduce it - however, simply changing which of the lines is commented out in `Main.hx` isn't enough. I need to comment out the `wtf.Crash` import as well for it not to crash.

**Comment by Cor-cor** [comment]
Yeah, should have mentioned that. Also just noticed that it's not obligatory to place state class into some exact directory to work, just into the same directory as the class that called the state. (So it won't need import statement.)

**Comment by Gama11** [comment]
> just into the same directory as the class that called the state

Not sure what you mean by that. In general or to reproduce this bug?

**Comment by Cor-cor** [comment]
To get around the bug.
For example, if I call `FlxG.switchState(new Bar())` from `Foo.hx` and then instantiate RadioGroup in `Bar.hx`, Foo and Bar classes should be in the same folder so I won't have to add `import somepackage.Bar` to `Foo.hx`. This way it works without crashing.

**Comment by Gama11** [comment]
Wow, so it really is the import... Using the qualified path works too:

```haxe
addChild(new FlxGame(600, 480, wtf.Crash, 1, 60, 60, true));
```

**Comment by Gama11** [comment]
This seems to be enough to reproduce:

```haxe
class Main extends openfl.display.Sprite {
    public function new() {
        super();
        new flixel.addons.ui.FlxUIList();
    }
}
```

No imports or additional files needed.

**Comment by Gama11** [comment]
Probably a Haxe regression, works in 3.2.1. :/

**Comment by Gama11** [comment]
Finally managed to isolate it: https://github.com/HaxeFoundation/haxe/issues/6196
