### ISSUE TITLE
Haxe 4 - `operator` is now reserved 

### ISSUE THREAD

**Issue by AustinEast** [HaxeFlixel/flixel-ui#213]
In Haxe 4, `operator` will be a reserved keyword. Currently variables with that name are dispersed throughout a couple of the classes in this repo, causing a build failure.

**Comment by rishavs** [comment]
Another compat issue can be that `private var _data:Fast;` is throwing `This typedef is deprecated in favor of haxe.xml.Access` on files like FlxUI.hx
