### ISSUE TITLE
idk what is this  but is from psych engine 0.7.1h source code compile

### ISSUE THREAD

**Issue by Snicktp** [HaxeFlixel/flixel-ui#260]
source/flixel/sound/FlxSound.hx:601: characters 16-24 : flash.media.SoundChannel has no field __source
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
source/flixel/sound/FlxSound.hx:605: characters 19-27 : flash.media.SoundChannel has no field __source
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
C:/Users/do you care?/nstall hscript/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
source/options/NotesSubState.hx:193: characters 48-60 : flixel.input.mouse.FlxMouse has no field deltaScreenX
source/options/NotesSubState.hx:193: characters 80-92 : flixel.input.mouse.FlxMouse has no field deltaScreenY
source/options/NotesSubState.hx:456: characters 62-71 : flixel.math.FlxPoint has no field degreesTo
source/options/NotesSubState.hx:457: characters 42-46 : flixel.math.FlxPoint has no field distsource/flixel/sound/FlxSound.hx:601: characters 16-24 : flash.media.SoundChannel has no field __source
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
source/flixel/sound/FlxSound.hx:605: characters 19-27 : flash.media.SoundChannel has no field __source
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
C:/Users/do you care?/nstall hscript/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
source/options/NotesSubState.hx:193: characters 48-60 : flixel.input.mouse.FlxMouse has no field deltaScreenX
source/options/NotesSubState.hx:193: characters 80-92 : flixel.input.mouse.FlxMouse has no field deltaScreenY
source/options/NotesSubState.hx:456: characters 62-71 : flixel.math.FlxPoint has no field degreesTo
source/options/NotesSubState.hx:457: characters 42-46 : flixel.math.FlxPoint has no field dist

**Comment by Geokureli** [comment]
this isn't flixel-ui related, it might be flixel related but you should start in the psych github or discord or FNF discord
