### ISSUE TITLE
QUESTION: Haxe Version

### ISSUE THREAD

**Issue by gamerbross** [HaxeFlixel/flixel-ui#273]
I'm planning doing a big pull request that refactors old code and fixes some stuff, do I to keep old haxe versions support or I can just use new features like null safety operators without checking the version

**Comment by Geokureli** [comment]
Make an issue describing the problems you see and the solutions you have for them. After we discus them you can make individual PRs to change specific issues. Large PRs swith sweeping changes for various issues rarely get accepted

**Comment by gamerbross** [comment]
ok thx!
