### ISSUE TITLE
[BUG] FlxUIDropDownMenu not working correctly

### ISSUE THREAD

**Issue by gamerbross** [HaxeFlixel/flixel-ui#274]
(I don't really know if it's version specific, but it affects last FNF version, in the Animation Editor)
How can be replicated in FNF:
- Open debug menu selector in main menu (tilde key)
- Select animatione editor
- Change to Animations mode
- Click the dropdown at the bottom right of the screen and change to other animation.
The problem is that the change callback isn't called when clicking an item, it gets callled after pressing the item and pressing the dropdown again.

The issue is because it tries to hide the drop panel before handling onUp of the items.

[`FlxUIDropDownMenu.update`](https://github.com/HaxeFlixel/flixel-ui/blob/master/flixel/addons/ui/FlxUIDropDownMenu.hx#L405C1-L418C3)

```haxe
public override function update(elapsed:Float):Void
{
	super.update(elapsed);

	#if FLX_MOUSE
	if (dropPanel.visible && FlxG.mouse.justPressed)
	{
		if (!FlxG.mouse.overlaps(this))
		{
			showList(false);
		}
	}
	#end
}
```

And this is my solution:
```haxe
public override function update(elapsed:Float):Void
{
	super.update(elapsed);

	#if FLX_MOUSE
	if (dropPanel.visible && FlxG.mouse.justPressed)
	{
		if (header.button.justPressed)
			return;

		for (button in list)
		{
			if (button.justPressed)
				return;
		}

		showList(false);
	}
	#end
}
```
It probably doesn't follow the code style, but shows the point, just checks if any button wasn't just pressed before hiding the list. (The list will hide anyway, it doesn't change the behaviour)

**Comment by Geokureli** [comment]
I appreciate you making this issue rather than jumping right in to a big PR, that said, it's always a good idea to try and replicate the issue in a new Flixel project. A lot of the HF maintainers aren't deeply familiar with FNF specific code and before we change stuff it needs to be determined that the problem isn't the result of bad FNF code rather than bad HaxeFlixel code.

Looking this over, it does seem like a flixel issue, and it looks like I should be able to reproduce this issue pretty easily, so if you would like to make a pr for this specific change, go right ahead and when you do, I'll make a little isolated test to verify it when I next have time available

**Comment by gamerbross** [comment]
After struggling how to replicate this, I finally got it
```haxe
package;

import flixel.FlxCamera;
import flixel.FlxG;
import flixel.FlxSprite;
import flixel.addons.ui.FlxUIDropDownMenu;
import flixel.text.FlxText;

class PlayState extends flixel.FlxState
{
	var dropdown:FlxUIDropDownMenu;
	var hudCam:FlxCamera;

	override public function create()
	{
		hudCam = new FlxCamera();
		FlxG.cameras.add(hudCam);

		var bg = new FlxSprite().makeGraphic(Std.int(FlxG.width / 2), Std.int(FlxG.height / 2), -1);
		bg.screenCenter();
		add(bg);

		var selectionText = new FlxText(10, 10, 0, "Current Selection: none");
		add(selectionText);
		dropdown = new FlxUIDropDownMenu(0, 0, FlxUIDropDownMenu.makeStrIdLabelArray(["hello", "world", "test123"], true), function(selection:String):Void {
			selectionText.text = 'Current Selection: $selection';
		});
		dropdown.cameras = [hudCam];
		dropdown.x = FlxG.width - dropdown.width - 10;
		dropdown.y = FlxG.height - dropdown.height - 10;
		add(dropdown);

		FlxG.camera.scroll.set(100, 100);
		super.create();
	}
}
```
This can be used on a blank haxeflixel project and will replicate the same bug as un FNF

**Comment by gamerbross** [comment]
oops i didnt mean to send it sorry

**Comment by gamerbross** [comment]
just updated the message (lmfao sorry for this idk how i pressed tab and enter)

**Comment by Geokureli** [comment]
Thanks! I'll try this out tomorrow

**Comment by gamerbross** [comment]
yes, just use the dropdown

**Comment by Geokureli** [comment]
yep def acting up
