### ISSUE TITLE
Game crashing because of Invalid FlxDrawItem when using FlxInputText

### ISSUE THREAD

**Issue by Arolox666** [HaxeFlixel/flixel-ui#283]
I was trying to make an username input text box but when I compiled the game it said this
![Screenshot 2024-09-26 194257](https://github.com/user-attachments/assets/74e7521f-dffb-400d-bc2e-7e2e885c2fa7)
Here is the code of how initialized the InputText
```haxe
        var userNameTextBox = new FlxInputText(367, 272, 1200, "Enter Username... (Max 40 Characters)", 48, 0xff000000, 0xffffff, true);
        userNameTextBox.font = "Arial";
        userNameTextBox.maxLength = 40;
        userNameTextBox.focusGained = () -> userNameTextBox.text = "";
        add(userNameTextBox);
```
P.S.: I tried using FlxUIInputText but the same thing happened.

**Comment by Geokureli** [comment]
A new FlxInputText is coming the core flixel in the next update, feel free to use
```
haxelib git flixel https://github.com/HaxeFlixel/flixel.git
```
To use the next release early, I'll look into this issue, though

**Comment by Arolox666** [comment]
> A new FlxInputText is coming the core flixel in the next update, feel free to use
> 
> ```
> haxelib git flixel https://github.com/HaxeFlixel/flixel.git
> ```
> 
> To use the next release early, I'll look into this issue, though

I tried to use the git but there is no FlxInputText in normal flixel imports.

**Comment by Geokureli** [comment]
> I tried to use the git but there is no FlxInputText in normal flixel imports.

https://github.com/HaxeFlixel/flixel/blob/dev/flixel/text/FlxInputText.hx

**Comment by Arolox666** [comment]
> > I tried to use the git but there is no FlxInputText in normal flixel imports.
> 
> https://github.com/HaxeFlixel/flixel/blob/dev/flixel/text/FlxInputText.hx

Oh sorry I'm just stupid and VS Code didn't detect that it exists
