### ISSUE TITLE
A lot of errors compiling Psych Engine 0.7.3

### ISSUE THREAD

**Issue by 6609sff3** [HaxeFlixel/flixel-ui#286]
Errors:

C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
Creating C:/Users/gabby/Downloads/FNF-PsychEngine-main/export/release/windows/obj/obj/msvc1964-nc/__pch/haxe/hxcpp.pch...
hxcpp.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory
Error: Could not create PCH

**Comment by moxie-coder** [comment]
This isn’t the right repo for this issue

**Comment by Geokureli** [comment]
Please create psych issues here
https://github.com/ShadowMario/FNF-PsychEngine/issues/new/choose
