### ISSUE TITLE
Change FlxUIWidget.id to name

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel-ui#31]
That's more intuitive in my opinion, with `id` you'd assume it's an integer, plus `FlxBasic` already has `public var ID:Int` which might lead to confusion.

**Comment by larsiusprime** [comment]
I should go ahead and do this, but it will break old versions of the project. Shall we add getter / setter for id that re-route to name, but with some kind of deprecation notice?

**Comment by Gama11** [comment]
Considering the amount of breaking changes in core flixel for 4.0.0, I don't think that would help too much.

**Comment by larsiusprime** [comment]
So just bite the bullet?

...is it possible to leave in a setter/getter for id that reroutes to name
that is somehow hidden from FD autocompletion?

On Mon, Jan 19, 2015 at 12:25 PM, Gama11 <notifications@github.com> wrote:

> Considering the amount of breaking changes in core flixel for 4.0.0, I
> don't think that would help too much.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HaxeFlixel/flixel-ui/issues/31#issuecomment-70538624>.
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by Gama11** [comment]
Not exactly, no. There's `@:noCompletion`, but that only works for Compiler completion, not FD's own completion (FD currently doesn't parse metadata, so it's just ignored) - might even cause some confusion when fields suddenly disappear after half a second or so (FD provides its own completion right away and replaces it with the results from compiler completion after they arrive).

**Comment by larsiusprime** [comment]
Alrighty, I can do this. How many places will I need to update it in flixel's various repositories?

**Comment by Gama11** [comment]
Just your flixel-ui demos in flixel-demos I think? Travis should tell you if you missed something I guess. :)

**Comment by larsiusprime** [comment]
Suppose so. I guess the most common use of "id" is in XML markup itself rather than directly in code, so it's probably not a HUGE change... I think I will go on supporting id in xml parsing, just sending it on to "name", but remove the id property in the objects themselves.

**Comment by larsiusprime** [comment]
https://github.com/HaxeFlixel/flixel-ui/pull/87

Review at your leisure and then maybe we can close this out.
