### ISSUE TITLE
FlxInputText background issues

### ISSUE THREAD

**Issue by Arcnor** [HaxeFlixel/flixel-ui#40]
* If you create a FlxInputText and later set `background` to false, the background is still drawn.
* If you set the `BackgroundColor` argument to 0 when creating the object, `background` will be set to false, but you'll get the same behavior.

The problem is that both the background and border sprites are still being created. Setting both to null when creating with a 0 background color or when changing `background` to false should fix this.

**Comment by larsiusprime** [comment]
This seems to have been fixed a while back. I can no longer reproduce any of these issues.
