### ISSUE TITLE
Adding custom buttons for keysClick

### ISSUE THREAD

**Issue by SeiferTim** [HaxeFlixel/flixel-ui#63]
I tried doing this:
```
cursor.keysClick.push(new MultiKey(FlxG.keys.getKeyCode("X")));
```
But pressing X only makes the button look like it's getting MouseOver and not being clicked.

**Comment by larsiusprime** [comment]
Boy, was this broken. It wasn't taking multiple click buttons into account and only the first would work. 

Fixed!
