### ISSUE TITLE
FlxUIButton label question

### ISSUE THREAD

**Issue by kdm2k6** [HaxeFlixel/flixel-ui#73]
If I change the label size via label.size it doesn't seem to recenter properly (unless I call calcFrame() after changing the size).. When I need to change a labels size should I just create a new FlxUITxt or am I supposed to be able to change the size property (without calling calcFrame())?

Thanks

**Comment by larsiusprime** [comment]
Label is a separate property and so there's no easy way to update the original button after you change the label's size. I recommend calling calcFrame() or autoCenterLabel() after updating the label's size.
