### ISSUE TITLE
a fix for FlxInputText filter not working

### ISSUE THREAD

**Issue by AG-w** [HaxeFlixel/flixel-ui#86]
in FlxInputText.hx a function called "filter"

pattern.replace(text, "");
should be
text = pattern.replace(text, "");

**Comment by larsiusprime** [comment]
Ah, good catch. You've confirmed it doesn't work without this?

**Comment by AG-w** [comment]
I haven't use filter before
http://haxeflixel.com/forum/?place=msg%2Fhaxeflixel%2FrYA_a1KPwQA%2F8ucLpnlbWZgJ
but I see someone posted this and I tried my self
