### ISSUE TITLE
Lists

### ISSUE THREAD

**Issue by Tiago-Ling** [HaxeFlixel/flixel-ui#9]
A very useful widget to have would be UI lists. There are countless features and variations we could add to this widget, but a good starting point in my opinion would be:
- A "simple" scrollable list base class, representing the list view container, to be controlled by mouse scroll or touch (i don't think we need arrow buttons, just the scroll bar, which could be visible only when the list is being scrolled);
- A skinnable list item base class. The item could have an image, aligned to the left or right, two textfields (one for name & one for description, or one for name & one for price, etc) and could act like a button (normal or toggle);
- A list controller / manager, with each the user can instantiate the list, choosing the type list, the type of list item, the list data (probably from xml), parent, etc.

Ideally the list manager class would have some form of dynamic item loading system, to avoid putting lots of items into the list view all at once, and this would be triggered when scrolling. The list items would basically be modifications or aggregation of other widgets (buttons, textfields, etc).

Of course these are all simple and somewhat abstract ideas, the best way to implement this widget may be different and it probably a good idea to take a look at other ui libraries for ideas.

**Comment by GimmickyApps** [comment]
Would it be worth re-opening this until FlxUIWidget is extended to actually cover the functionality of a scrollable list widget?

**Comment by GimmickyApps** [comment]
This is not at all flixel-ui-integrated, and you would have to do the list managing yourself, but it's at least HaxeFlixel, if anybody stumbles across this thread looking for the same thing I was:
https://github.com/GimmickyApps/HaxeFlixelScrollableArea
