### ISSUE TITLE
Class cast error in openfl-next

### ISSUE THREAD

**Issue by larsiusprime** [HaxeFlixel/flixel-ui#99]
This only seems to happen when using -Dnext, and it may very well be an openfl issue and not a flixel issue, but I'm reporting it here for now.

In short, something about FlxUIRadioGroups causes a crash in next but not in legacy.

To reproduce:
```lime test neko -Dnext``` for the [RPG Interface](https://github.com/HaxeFlixel/flixel-demos/tree/dev/User%20Interface/RPG%20Interface) demo

```
T:\Development\Git\flixel-demos\User Interface\RPG Interface>lime test neko -Dne
xt
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Called from ? line 1
Called from ApplicationMain.hx line 130
Called from ApplicationMain.hx line 63
Called from lime/app/Application.hx line 158
Called from lime/_backend/native/NativeApplication.hx line 102
Called from lime/app/Event.hx line 59
Called from lime/app/Application.hx line 519
Called from openfl/display/Stage.hx line 882
Called from openfl/display/DisplayObjectContainer.hx line 661
Called from openfl/display/DisplayObject.hx line 985
Called from openfl/events/EventDispatcher.hx line 266
Called from flixel/FlxGame.hx line 531
Called from flixel/FlxGame.hx line 687
Called from flixel/FlxGame.hx line 707
Called from flixel/FlxGame.hx line 622
Called from State_Title.hx line 35
Called from flixel/addons/ui/FlxUIState.hx line 181
Called from flixel/addons/ui/FlxUIState.hx line 291
Called from flixel/addons/ui/FlxUI.hx line 652
Called from flixel/addons/ui/FlxUI.hx line 701
Called from flixel/addons/ui/FlxUI.hx line 1253
Called from flixel/addons/ui/FlxUI.hx line 2077
Called from flixel/addons/ui/FlxUIRadioGroup.hx line 14
Called from flixel/addons/ui/FlxUIRadioGroup.hx line 115
Called from flixel/addons/ui/FlxUIRadioGroup.hx line 186
Called from flixel/addons/ui/FlxUIRadioGroup.hx line 380
Called from flixel/addons/ui/FlxUIRadioGroup.hx line 442
Uncaught exception - Class cast error
```

**Comment by larsiusprime** [comment]
The line in question seems to be this:
```Haxe
var cs:CheckStyle = new CheckStyle(0xFFFFFF, FontDef.copyFromFlxText(t), t.alignment, t.color, new BorderDef(t.borderStyle, t.borderColor, t.borderSize, t.borderQuality));
```

Which on the repo is here:

**Comment by Beeblerox** [comment]
but why do you cast to? `cs` variable is already has required type (or maybe i'm missing somethig)

**Comment by larsiusprime** [comment]
@Beeblerox It's interesting, because it doesn't look like there's a cast anywhere in that line! So I think the cast must be happening in one of the functions called on that line?

**Comment by Beeblerox** [comment]
@larsiusprime how is there no cast in this line?
```
var cs = cast new CheckStyle(0xFFFFFF, fd, t.alignment, t.color, bd);
```
do you see `cast` keyword right after `=` sign?

**Comment by larsiusprime** [comment]
Ah, so there is! I was looking at an older version of it.

**Comment by larsiusprime** [comment]
Okay, I've removed the cast locally, and I found that it crashes in two places:

Here:
https://github.com/HaxeFlixel/flixel-ui/blob/dev/flixel/addons/ui/FlxUIRadioGroup.hx#L442

And here:
https://github.com/HaxeFlixel/flixel-ui/blob/dev/flixel/addons/ui/FlxUI.hx#L2101

What's interesting is if I change it do be something like this:
```Haxe
var cs = new CheckStyle(0xFFFFFF);
```

And leave off the other parameters, it will not crash. So something is happening there. I'm going to narrow down which one it is now.

**Comment by larsiusprime** [comment]
Interesting.

If I try to do this before the "new CheckStyle()" call:
```trace("t.alignment = " + t.alignment);```

I get an immediate crash on the same line I trace, with the same error - "Class cast error."

Looking at FlxTextAlign:

```
@:enum
abstract FlxTextAlign(String) from String
{
	var LEFT = "left";
	var CENTER = "center";
	var RIGHT = "right";
	var JUSTIFY = "justify";
}
```

I'm wondering if there was a subtle change in how this is handled, perhaps in Haxe itself. 

This definition has the @:enum tag, so I assume that means that ONLY these exact values are valid. I wonder if something other than one of these four values got passed in somehow (say null or ""), and that means whenever you try to cast it implicitly to a string (by using it) it freaks out and crashes because it doesn't match.

**Comment by larsiusprime** [comment]
Alrighty, I think I found our problem.

Take a look at openfl's TextFormatAlign:
https://github.com/openfl/openfl/blob/master/openfl/text/TextFormatAlign.hx

If we're in legacy mode we'll use this one:
https://github.com/openfl/openfl/blob/master/openfl/_legacy/text/TextFormatAlign.hx

```
class TextFormatAlign 
{
	public static var LEFT = "left";
	public static var RIGHT = "right";
	public static var CENTER = "center";
	public static var JUSTIFY = "justify";
}
```

If we're in next mode it uses this one:

```
enum TextFormatAlign {
	LEFT;
	RIGHT;
	JUSTIFY;
	CENTER;
}
```

I bet that has a lot to do with it.

**Comment by larsiusprime** [comment]
Okay, doing some more detective work.

```Haxe
/**
	private function convertTextAlignmentFromString(StrAlign:FlxTextAlign)
	{
		return switch (StrAlign)
		{
			case LEFT:
				TextFormatAlign.LEFT;
			case CENTER:
				TextFormatAlign.CENTER;
			case RIGHT:
				TextFormatAlign.RIGHT;
			case JUSTIFY:
				TextFormatAlign.JUSTIFY;
			default:
				throw "nuclear garbage!";
		}
	}
```

I added that last error to my local copy, suspecting some bad data is being passed in.

That gives me this stack trace:
```
Called from flixel/addons/ui/FlxUIRadioGroup.hx line 14
Called from flixel/addons/ui/FlxUIRadioGroup.hx line 115
Called from flixel/addons/ui/FlxUIRadioGroup.hx line 186
Called from flixel/addons/ui/FlxUIRadioGroup.hx line 378
Called from flixel/addons/ui/FlxUIButton.hx line 142
Called from flixel/text/FlxText.hx line 447
Called from flixel/text/FlxText.hx line 648
Called from flixel/text/FlxText.hx line 982
Uncaught exception - nuclear garbage!
```

That takes me to this interesting place:
https://github.com/HaxeFlixel/flixel-ui/blob/dev/flixel/addons/ui/FlxUIButton.hx#L142

```Haxe
label.setFormat(null, tf.size, tf.color, cast tf.align, t.borderStyle, t.borderColor, t.embedded);
```

"tf" in this case is an OpenFL textFormat object. We're passing it into label's setFormat, and label is a FlxUIText. It's setFormat calls for a FlxTextAlignment, not an openfl.text.TextFormatAlign.

Previously this was not an issue as they both were basically strings, but in -next openfl's TextFormatAlign is a strict enum, so this fails.

I'm going to try to do a safer operation than a naive cast and see if that fixes the issue.

**Comment by larsiusprime** [comment]
GOT IT.

This line causes all sorts of problems:
https://github.com/HaxeFlixel/flixel/blob/dev/flixel/text/FlxText.hx#L642

We need an explicit conversion function back and forth between FlxTextAlign and OpenFL's TextFormatAlign that is neatly wrapped and compatible between legacy/next.

I think the cleanest solution is to add public static to/from functions to FlxTextAlign:

```Haxe
@:enum
abstract FlxTextAlign(String) from String
{
	var LEFT = "left";
	var CENTER = "center";
	var RIGHT = "right";
	var JUSTIFY = "justify";
	
	#if !openfl_legacy
	public static function fromOpenFL(tf:TextFormatAlign):FlxTextAlign
	#else
	public static function fromOpenFL(tf:String):FlxTextAlign
	#end
	{
		//ifs instead of a switch b/c you can only switch on lower-case variable names and TextFormatAlign are all caps constants in legacy
		if (tf == TextFormatAlign.LEFT) return FlxTextAlign.LEFT;
		if (tf == TextFormatAlign.RIGHT) return FlxTextAlign.RIGHT;
		if (tf == TextFormatAlign.CENTER) return FlxTextAlign.CENTER;
		if (tf == TextFormatAlign.JUSTIFY) return FlxTextAlign.JUSTIFY;
		throw "illegal TextFormatAlign value!";
	}
	
	#if !openfl_legacy
	public static function toOpenFL(str:FlxTextAlign):TextFormatAlign
	#else
	public static function toOpenFL(str:FlxTextAlign):String
	#end
	{
		//ifs instead of a switch b/c you can only switch on lower-case variable names and TextFormatAlign are all caps constants in legacy
		if (str == LEFT) return TextFormatAlign.LEFT;
		if (str == RIGHT) return TextFormatAlign.RIGHT;
		if (str == CENTER) return TextFormatAlign.CENTER;
		if (str == JUSTIFY) return TextFormatAlign.JUSTIFY;
		throw "illegal FlxTextAlign value!";
	}
}
```

The conditional compilation is necessary because in next, TextFormatAlign is an actual enum class, but in legacy it's just a holder for public static string constants, so there is no actual "TextFormatAlign" type.

Furthermore, I can't use a switch statement because that won't compile in legacy, because there the  values are not enum members but string constants, and the Haxe compiler insists that the variables be lower-case. I mean I *could* use a switch statement but then I'd have to add more conditional compilation and this seemed cleaner and easier.

I'd post the other changes but I think it's easier to just issue a PR and we can discuss it further there:
https://github.com/HaxeFlixel/flixel/pull/1474
https://github.com/HaxeFlixel/flixel-ui/pull/100

**Comment by larsiusprime** [comment]
PR's got merged. Closing.
